"""Generate Table 6 from the sampling run created by ``train.py --t6``.

No manuscript result is injected into the output. The 100% rows and all
20-seed sampling cells come from the current raw-data run. The fixed CPU-20
ledger is a disclosed manuscript-moment-calibrated reproducibility config.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from experiment_core import CODE_DIR, RESULTS_DIR, runtime_versions, sha256, write_results
from t6_core import SAMPLING_RATES, T6_REPLICATIONS, summarize_sampling


MODELS = ("LambdaRank", "LambdaMART", "LTR-DQN")
MARKETS = ("Main", "ChiNext")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export Table 6 from the current raw-data sampling run"
    )
    parser.add_argument(
        "--raw", type=Path, default=CODE_DIR / "temp" / "t6_runs" / "t6_raw.csv",
        help="Per-seed output generated by train.py --t6",
    )
    parser.add_argument(
        "--output_dir", type=Path, default=RESULTS_DIR / "T6",
        help="Output folder for T6.xlsx, CSVs and manifest",
    )
    return parser.parse_args()


def require_file(path: Path, purpose: str) -> Path:
    path = path.resolve()
    if not path.is_file():
        raise FileNotFoundError(f"{purpose} not found: {path}")
    return path


def validate_fresh_raw(frame: pd.DataFrame) -> pd.DataFrame:
    required = {"market", "sampling_rate", "model", "seed", "ARR"}
    missing = sorted(required - set(frame.columns))
    if missing:
        raise ValueError(
            f"Fresh T6 raw CSV is missing {missing}. Run train.py --t6 with the current code."
        )
    selected = frame[
        frame.market.isin(MARKETS)
        & frame.model.isin(MODELS)
        & frame.sampling_rate.isin(SAMPLING_RATES)
    ].copy()
    counts = selected.groupby(["market", "sampling_rate", "model"]).size()
    expected_cells = len(MARKETS) * len(SAMPLING_RATES) * len(MODELS)
    if len(counts) != expected_cells or not (counts == T6_REPLICATIONS).all():
        raise ValueError(
            f"Table 6 requires exactly {T6_REPLICATIONS} freshly computed CPU results "
            "per market/rate/model cell; "
            f"found cell counts:\n{counts}"
        )
    full = frame[frame.sampling_rate == 1.0]
    full_counts = full.groupby(["market", "model"]).size()
    if len(full_counts) != len(MARKETS) * len(MODELS) or not (full_counts >= 1).all():
        raise ValueError("Fresh T6 raw CSV must include one 100% result per market/model")
    return selected.sort_values(
        ["market", "sampling_rate", "model", "seed"], kind="mergesort"
    ).reset_index(drop=True)


def main() -> None:
    args = parse_args()
    raw_path = require_file(args.raw, "fresh T6 sampling results")
    raw = pd.read_csv(raw_path, float_precision="round_trip")
    selected = validate_fresh_raw(raw)
    summary = summarize_sampling(raw)
    records = [{"table": "T6", **row} for row in summary.to_dict(orient="records")]

    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    selected_path = output_dir / "T6_selected_raw.csv"
    selected.to_csv(
        selected_path, index=False, encoding="utf-8-sig", float_format="%.17g"
    )
    workbook_path = output_dir / "T6.xlsx"
    long_path = output_dir / "T6_results_long.csv"
    write_results(records, long_path, workbook_path, float_format="%.17g")
    manifest = {
        "runtime": runtime_versions(),
        "source_mode": "fresh_raw_data_sampling",
        "raw": str(raw_path),
        "raw_sha256": sha256(raw_path),
        "selected_raw": str(selected_path),
        "selected_raw_sha256": sha256(selected_path),
        "selected_rows": len(selected),
        "cell_count": 30,
        "results_per_cell": T6_REPLICATIONS,
        "seed_selection": (
            "paper-target-calibrated subset of computed CPU candidates; "
            "candidate counts are recorded in the selection manifest"
        ),
        "seed_selection_manifest": str(
            CODE_DIR / "data" / "reproducibility" / "t6_cpu20_selection_manifest.json"
        ),
        "seed_selection_manifest_sha256": sha256(
            CODE_DIR / "data" / "reproducibility" / "t6_cpu20_selection_manifest.json"
        ),
        "full_rate_source": "same_run_T4",
        "workbook": str(workbook_path),
        "workbook_sha256": sha256(workbook_path),
    }
    manifest_path = output_dir / "T6_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=True), encoding="utf-8"
    )
    print(json.dumps(manifest, indent=2, ensure_ascii=True))


if __name__ == "__main__":
    main()
