"""Generate Table 6 from the sampling run created by ``train.py --t6``.

No manuscript values or historical exhaustive-search outputs are consumed.
The 100% rows and all 500-seed sampling cells come from the current raw-data
run, while the recorded seed ledgers are treated as reproducibility config.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from experiment_core import (
    CODE_DIR,
    RESULTS_DIR,
    runtime_versions,
    sha256,
    validate_runtime,
    write_results,
)
from t6_core import SAMPLING_RATES, summarize_sampling


MODELS = ("LambdaRank", "LambdaMART", "LTR-DQN")
MARKETS = ("Main", "ChiNext")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export Table 6 from the current raw-data sampling run"
    )
    parser.add_argument(
        "--raw", type=Path, action="append", default=None,
        help="Per-seed output generated by train.py --t6; may be repeated",
    )
    parser.add_argument(
        "--raw_dir", type=Path, default=None,
        help="Recursively find t6_raw.csv files downloaded from parallel shards",
    )
    parser.add_argument(
        "--output_dir", type=Path, default=RESULTS_DIR / "T6",
        help="Output folder for T6.xlsx, CSVs and manifest",
    )
    parser.add_argument(
        "--skip_figure", action="store_true",
        help="Do not generate Appendix Figure C4",
    )
    return parser.parse_args()


def require_file(path: Path, purpose: str) -> Path:
    path = path.resolve()
    if not path.is_file():
        raise FileNotFoundError(f"{purpose} not found: {path}")
    return path


def validate_fresh_raw(frame: pd.DataFrame) -> pd.DataFrame:
    required = {"market", "sampling_rate", "model", "seed", "ARR"}
    missing = sorted(required - set(frame.columns))
    if missing:
        raise ValueError(
            f"Fresh T6 raw CSV is missing {missing}. Run train.py --t6 with the current code."
        )
    selected = frame[
        frame.market.isin(MARKETS)
        & frame.model.isin(MODELS)
        & frame.sampling_rate.isin(SAMPLING_RATES)
    ].copy()
    counts = selected.groupby(["market", "sampling_rate", "model"]).size()
    expected_cells = len(MARKETS) * len(SAMPLING_RATES) * len(MODELS)
    if len(counts) != expected_cells or not (counts == 500).all():
        raise ValueError(
            "Table 6 requires exactly 500 freshly computed results per market/rate/model cell; "
            f"found cell counts:\n{counts}"
        )
    full = frame[frame.sampling_rate == 1.0]
    full_counts = full.groupby(["market", "model"]).size()
    if len(full_counts) != len(MARKETS) * len(MODELS) or not (full_counts >= 1).all():
        raise ValueError("Fresh T6 raw CSV must include one 100% result per market/model")
    return selected.sort_values(
        ["market", "sampling_rate", "model", "seed"], kind="mergesort"
    ).reset_index(drop=True)


def raw_input_paths(args: argparse.Namespace) -> list[Path]:
    paths = list(args.raw or [])
    if args.raw_dir is not None:
        paths.extend(sorted(args.raw_dir.resolve().rglob("t6_raw.csv")))
    if not paths:
        paths.append(CODE_DIR / "temp" / "t6_runs" / "t6_raw.csv")
    resolved = []
    for path in paths:
        current = require_file(path, "fresh T6 sampling results")
        if current not in resolved:
            resolved.append(current)
    return resolved


def load_raw_inputs(paths: list[Path]) -> pd.DataFrame:
    frames = [pd.read_csv(path) for path in paths]
    merged = pd.concat(frames, ignore_index=True, sort=False)
    required = ["market", "sampling_rate", "model", "seed"]
    if all(column in merged for column in required):
        merged = merged.drop_duplicates(required, keep="last")
        if "sequence_position" in merged and merged["sequence_position"].notna().all():
            merged = merged.sort_values("sequence_position", kind="mergesort")
        elif len(paths) > 1:
            raise ValueError(
                "Parallel T6 inputs do not contain sequence_position. "
                "Regenerate the shards with the current t6_shard_runner.py."
            )
        merged = merged.reset_index(drop=True)
    return merged


def main() -> None:
    args = parse_args()
    validate_runtime()
    raw_paths = raw_input_paths(args)
    raw = load_raw_inputs(raw_paths)
    selected = validate_fresh_raw(raw)
    summary = summarize_sampling(raw)
    records = [{"table": "T6", **row} for row in summary.to_dict(orient="records")]

    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    combined_raw_path = output_dir / "T6_raw_combined.csv"
    raw.to_csv(combined_raw_path, index=False, encoding="utf-8-sig")
    selected_path = output_dir / "T6_selected_raw.csv"
    selected.to_csv(selected_path, index=False, encoding="utf-8-sig")
    workbook_path = output_dir / "T6.xlsx"
    long_path = output_dir / "T6_results_long.csv"
    write_results(records, long_path, workbook_path)
    figure_path = None
    if not args.skip_figure:
        from Appendix_Fig_main import compute_c4, plot_c4

        figure_dir = RESULTS_DIR / "appendix_figures"
        figure_data_dir = figure_dir / "data"
        figure_data_dir.mkdir(parents=True, exist_ok=True)
        figure_data_path = figure_data_dir / "FigC4_sampling_ARR.csv"
        figure_frame = compute_c4(selected_path, figure_data_path, force=True)
        figure_path = figure_dir / "FigC4_sampling_robustness_boxplots.png"
        plot_c4(figure_frame, figure_path)
    manifest = {
        "runtime": runtime_versions(),
        "source_mode": "fresh_raw_data_sampling",
        "raw_inputs": {str(path): sha256(path) for path in raw_paths},
        "combined_raw": str(combined_raw_path),
        "combined_raw_sha256": sha256(combined_raw_path),
        "selected_raw": str(selected_path),
        "selected_raw_sha256": sha256(selected_path),
        "selected_rows": len(selected),
        "cell_count": 30,
        "results_per_cell": 500,
        "full_rate_source": "fresh_100_percent_rows",
        "workbook": str(workbook_path),
        "workbook_sha256": sha256(workbook_path),
        "figure_c4": str(figure_path) if figure_path else None,
        "figure_c4_sha256": sha256(figure_path) if figure_path else None,
    }
    manifest_path = output_dir / "T6_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=True), encoding="utf-8"
    )
    print(json.dumps(manifest, indent=2, ensure_ascii=True))


if __name__ == "__main__":
    main()
